{% set name = "types-itsdangerous" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-itsdangerous-{{ version }}.tar.gz
  sha256: e3085cdfb0554b601c29635eec6af0b39abc717ff078d16b15eeaba778c13b6e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/itsdangerous-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for itsdangerous
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
